---
version: 2.1

parameters:
    run_workflow_deploy:
      type: boolean
      default: true
  
    # Every build below can be activated by setting default to true (or deactivated by setting default: false)
    build_android_arm64:
      type: boolean
      default: false
    build_android_armhf:
      type: boolean
      default: false
  
    build_flatpak_aarch64_2208:
      type: boolean
      default: false
    build_flatpak_x86_2208:
      type: boolean
      default: false
    build_flatpak_aarch64_2408:
      type: boolean
      default: false
    build_flatpak_x86_2408:
      type: boolean
      default: false
  
    build_msvc_wx32_2022:
      type: boolean
      default: false
  
    build_debian_armhf_13_trixie:
      type: boolean
      default: false
    build_debian_arm64_13_trixie:
      type: boolean
      default: false
    build_debian_x86_64_13_trixie:
      type: boolean
      default: false
  
    build_debian_arm64_12_bookworm:
      type: boolean
      default: false
    build_debian_armhf_12_bookworm:
      type: boolean
      default: false
    build_debian_x86_64_12_bookworm:
      type: boolean
      default: false
  
    build_debian_armhf_11_bullseye:
      type: boolean
      default: false
    build_debian_arm64_11_bullseye:
      type: boolean
      default: false
    build_debian_x86_64_11_bullseye:
      type: boolean
      default: false
  
    build_ubuntu_x86_64_2204_jammy:
      type: boolean
      default: false
  
    build_macos_universal:
      type: boolean
      default: true

    #build_msvc_2022:
    #  type: boolean
    #  default: false

std-filters: &std-filters
    filters:
        branches:
            ignore:
            - devel
            - tmp
        tags:
            only: /.*/

workflows:
   build-android-arm64-wf:
       when: << pipeline.parameters.build_android_arm64 >>
       jobs:
         - build-android-arm64:
             <<: *std-filters
    
   build-android-armhf-wf:
       when: << pipeline.parameters.build_android_armhf >>
       jobs:
         - build-android-armhf:
             <<: *std-filters
    
   build-flatpak-aarch64-2208-wf:
       when: << pipeline.parameters.build_flatpak_aarch64_2208 >>
       jobs:
         - build-flatpak-aarch64-2208:
             <<: *std-filters
    
   build-flatpak-x86-2208-wf:
       when: << pipeline.parameters.build_flatpak_x86_2208 >>
       jobs:
         - build-flatpak-x86-2208:
             <<: *std-filters
    
   build-flatpak-aarch64-2408-wf:
       when: << pipeline.parameters.build_flatpak_aarch64_2408 >>
       jobs:
         - build-flatpak-aarch64-2408:
             <<: *std-filters
    
   build-flatpak-x86-2408-wf:
       when: << pipeline.parameters.build_flatpak_x86_2408 >>
       jobs:
         - build-flatpak-x86-2408:
             <<: *std-filters
    
   build-msvc-wx32-2022-wf:
       when: << pipeline.parameters.build_msvc_wx32_2022 >>
       jobs:
         - build-msvc-wx32-2022:
             <<: *std-filters
    
   build-debian-armhf-13-trixie-wf:
       when: << pipeline.parameters.build_debian_armhf_13_trixie >>
       jobs:
         - build-debian-armhf-13-trixie:
             <<: *std-filters
    
   build-debian-arm64-13-trixie-wf:
       when: << pipeline.parameters.build_debian_arm64_13_trixie >>
       jobs:
         - build-debian-arm64-13-trixie:
             <<: *std-filters
    
   build-debian-x86_64-13-trixie-wf:
       when: << pipeline.parameters.build_debian_x86_64_13_trixie >>
       jobs:
         - build-debian-x86_64-13-trixie:
             <<: *std-filters
    
   build-debian-arm64-12-bookworm-wf:
       when: << pipeline.parameters.build_debian_arm64_12_bookworm >>
       jobs:
         - build-debian-arm64-12-bookworm:
             <<: *std-filters
    
   build-debian-armhf-12-bookworm-wf:
       when: << pipeline.parameters.build_debian_armhf_12_bookworm >>
       jobs:
         - build-debian-armhf-12-bookworm:
             <<: *std-filters
    
   build-debian-x86_64-12-bookworm-wf:
       when: << pipeline.parameters.build_debian_x86_64_12_bookworm >>
       jobs:
         - build-debian-x86_64-12-bookworm:
             <<: *std-filters
    
   build-debian-armhf-11-bullseye-wf:
       when: << pipeline.parameters.build_debian_armhf_11_bullseye >>
       jobs:
         - build-debian-armhf-11-bullseye:
             <<: *std-filters
    
   build-debian-arm64-11-bullseye-wf:
       when: << pipeline.parameters.build_debian_arm64_11_bullseye >>
       jobs:
         - build-debian-arm64-11-bullseye:
             <<: *std-filters
    
   build-debian-x86_64-11-bullseye-wf:
       when: << pipeline.parameters.build_debian_x86_64_11_bullseye >>
       jobs:
         - build-debian-x86_64-11-bullseye:
             <<: *std-filters
    
   build-ubuntu-x86_64-2204-jammy-wf:
       when: << pipeline.parameters.build_ubuntu_x86_64_2204_jammy >>
       jobs:
         - build-ubuntu-x86_64-2204-jammy:
             <<: *std-filters
    
   build-macos-universal-wf:
       when: << pipeline.parameters.build_macos_universal >>
       jobs:
         - build-macos-universal:
             <<: *std-filters

## -------------------------------------------
## OpenCPN 5.6.2 Plugins  Frozen - 28/05/2023
## ------------------------------------------
## Circleci will not build for macos 11 so removed - 18/10/2023
#   build-msvc-2022-wf:
#       when: << pipeline.parameters.build_msvc_2022 >>
#       jobs:
#         - build-msvc-2022:
#             <<: *std-filters


orbs:
    cloudsmith: cloudsmith/cloudsmith@1.0.5
    win: circleci/windows@5.1.0
    jq: circleci/jq@3.0.2

commands:
    deploy-code:
        parameters:
            install_python:
                type: boolean
                default: false
            deploy_use_orb:
                type: boolean
                default: true
        steps:
            - when:
                condition: <<pipeline.parameters.run_workflow_deploy>>
                steps:
                - when:
                    condition: <<parameters.install_python>>
                    steps:
                    - run: sudo apt install -y python3-pip
                    - run: python3 -m pip install cloudsmith-cli
                - when:
                    condition: <<parameters.deploy_use_orb>>
                    steps:
                    - cloudsmith/ensure-api-key
                    - cloudsmith/install-cli
                - get-users-and-collaborators
                - run: bash ci/cloudsmith-upload.sh
    get-collaborators:
      steps:
        - jq/install
        - run:
            name: "Get github collaborators"
            command: |
              if [ ! -z ${GITHUB_TOKEN+x} ]; then
                ghrc=$(curl -L -H "Accept: application/vnd.github+json" -H "Authorization: Bearer ${GITHUB_TOKEN}" -H "X-GitHub-Api-Version: 2022-11-28" https://api.github.com/repos/${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME}/collaborators?affiliation=direct)
              else
                ghrc=""
              fi
              collab_users=$(echo $ghrc | jq '.[].login')
              collab_users=$(echo $collab_users | sed 's/\"/;/g' | sed 's/;;/;/g' | tr -d '\n')
              echo "export collab_users=\"$collab_users\"" >> $BASH_ENV
    get-git-user:
      steps:
        - jq/install
        - run:
            name: "Get github user"
            command: |
              curl_resp=$(curl -s -S https://circleci.com/api/v2/pipeline/${CIRCLE_PIPELINE_ID})
              git_user=$(echo $curl_resp | jq '.trigger.actor.login')
              echo "export git_user=\"$git_user\"" >> $BASH_ENV
    get-users-and-collaborators:
      steps:
        - get-collaborators
        - get-git-user

jobs:
    build-android-arm64:
        docker:
        - image: cimg/android:2023.12-ndk
        resource_class: large
        environment:
        - OCPN_TARGET:  android-arm64
        - DEPLOY_USE_ORB: true
        - INSTALL_PYTHON: true
        steps:
        - checkout
        - run: chmod a+x ci/*.sh
        - run: bash ci/circleci-build-android-arm64.sh
        - deploy-code:
            install_python: true
    build-android-armhf:
        docker:
        - image: cimg/android:2022.12-ndk
        resource_class: large
        environment:
        - OCPN_TARGET:  android-armhf
        - DEPLOY_USE_ORB: true
        - INSTALL_PYTHON: true
        steps:
        - checkout
        - run: chmod a+x ci/*.sh
        - run: bash ci/circleci-build-android-armhf.sh
        - deploy-code:
            install_python: true
    build-macos-universal:
        macos:
            xcode: 15.4.0
        environment:
            OCPN_TARGET: macos
            CMAKE_BUILD_PARALLEL_LEVEL: 2
            WX_VER: 32
            DEPLOY_USE_ORB: false
            INSTALL_PYTHON: false
        steps:
        - checkout
        - run: sudo chmod go+w /usr/local
        - restore_cache:
            key: "{{checksum \"build-deps/macos-cache-stamp\"}}\
              -{{checksum \"cmake/MacosWxwidgets.cmake\"}}\
              -{{checksum \"ci/circleci-build-macos-universal.sh\"}}"
        - run: chmod a+x ci/*.sh
        - run: chmod a+x cmake/*.sh
        - run: ci/circleci-build-macos-universal.sh
        - save_cache:
            key: "{{checksum \"build-deps/macos-cache-stamp\"}}\
              -{{checksum \"cmake/MacosWxwidgets.cmake\"}}\
              -{{checksum \"ci/circleci-build-macos-universal.sh\"}}"
            paths:
              - /tmp/local.cache.tar
              - /Users/distiller/project/cache
        - run: >
              sh -c "otool -L build/*.dylib"
        - run: >
              sh -c "cat build/*.xml"
        - deploy-code:
            deploy_use_orb: false
            install_python: false
    build-msvc-wx32-2022:
        executor:
            name: win/server-2022
            shell: bash.exe
        environment:
        - OCPN_TARGET: MSVC
        - MSVC_VERSION: 2022
        - WX_VER: 32
        - DEPLOY_USE_ORB: false
        - APPVEYOR: 1 
        - CI: ""
        steps:
        - checkout
        - run:
            privileged: False
            shell: cmd.exe
            command: ci\circleci-build-msvc.bat
            no_output_timeout: 30m
        - deploy-code:
            deploy_use_orb: false

    build-flatpak-aarch64-2208:
        machine:
            image: ubuntu-2404:current
            resource_class: arm.medium
        environment:
        - OCPN_TARGET:  flatpak
        - BUILD_ARCH: aarch64
        - FLATPAK_BRANCH: stable
        - CLOUDSMITH_PKG_EXT: gz
        - SDK_VER: 22.08
        - DEPLOY_USE_ORB: true
        steps:
        - checkout
        - run: chmod a+x ci/*.sh
        - run:
            command: bash ci/circleci-build-flatpak.sh
        - deploy-code
    build-flatpak-x86-2208:
        machine:
            image: ubuntu-2404:current
        environment:
        - OCPN_TARGET:  flatpak
        - BUILD_ARCH: x86_64
        - FLATPAK_BRANCH: stable
        - CLOUDSMITH_PKG_EXT: gz
        - SDK_VER: 22.08
        - DEPLOY_USE_ORB: true
        steps:
        - checkout
        - run: chmod a+x ci/*.sh
        - run:
            command: bash ci/circleci-build-flatpak.sh
            no_output_timeout: 30m
        - deploy-code
    build-flatpak-aarch64-2408:
        machine:
            image: ubuntu-2404:current
            resource_class: arm.medium
        environment:
        - OCPN_TARGET:  flatpak
        - BUILD_ARCH: aarch64
        - FLATPAK_BRANCH: stable
        - CLOUDSMITH_PKG_EXT: gz
        - SDK_VER: 24.08
        - DEPLOY_USE_ORB: true
        steps:
        - checkout
        - run: chmod a+x ci/*.sh
        - run:
            command: bash ci/circleci-build-flatpak.sh
        - deploy-code
    build-flatpak-x86-2408:
        machine:
            image: ubuntu-2404:current
        environment:
        - OCPN_TARGET:  flatpak
        - BUILD_ARCH: x86_64
        - FLATPAK_BRANCH: stable
        - CLOUDSMITH_PKG_EXT: gz
        - SDK_VER: 24.08
        - DEPLOY_USE_ORB: true
        steps:
        - checkout
        - run: chmod a+x ci/*.sh
        - run:
            command: bash ci/circleci-build-flatpak.sh
            no_output_timeout: 30m
        - deploy-code
    build-debian-arm64-13-trixie:
        machine:
            image: ubuntu-2204:current
            resource_class: arm.medium
        environment:
        - OCPN_TARGET: trixie-arm64
        - DOCKER_IMAGE: arm64v8/debian:trixie
        - BUILD_FLAGS: -j3
        - BUILD_ENV: debian
        - WX_VER: 32
        - BUILD_GTK3: true
        - DEPLOY_USE_ORB: true
        steps:
        - checkout
        - run: chmod a+x ./ci/*.sh
        - run:
            command: ci/circleci-build-ubuntu-docker.sh
            no_output_timeout: 30m
        - deploy-code
    build-debian-armhf-13-trixie:
        machine:
            image: ubuntu-2204:current
            resource_class: arm.medium
        environment:
        - OCPN_TARGET: trixie-armhf
        - DOCKER_IMAGE: arm32v7/debian:trixie
        - BUILD_FLAGS: -j3
        - BUILD_ENV: debian
        - WX_VER: 32
        - BUILD_GTK3: true
        - DEPLOY_USE_ORB: true
        steps:
        - checkout
        - run: chmod a+x ./ci/*.sh
        - run:
            command: ci/circleci-build-ubuntu-docker.sh
            no_output_timeout: 30m
        - deploy-code
    build-debian-x86_64-13-trixie:
        machine:
            image: ubuntu-2404:current
        environment:
        - OCPN_TARGET: trixie
        - BUILD_GTK3: true
        - WX_VER: 32
        - DEPLOY_USE_ORB: true
        - BUILD_ENV: debian
        - DOCKER_IMAGE: debian:trixie
        steps:
        - checkout
        - run: chmod a+x ci/*.sh
        - run:
            command: ci/circleci-build-ubuntu-docker.sh
            no_output_timeout: 30m
        - deploy-code
    build-debian-arm64-12-bookworm:
        machine:
            image: ubuntu-2204:current
            resource_class: arm.medium
        environment:
        - OCPN_TARGET: bookworm-arm64
        - DOCKER_IMAGE: arm64v8/debian:bookworm
        - BUILD_FLAGS: -j3
        - BUILD_ENV: debian
        - WX_VER: 32
        - BUILD_GTK3: true
        - DEPLOY_USE_ORB: true
        steps:
        - checkout
        - run: chmod a+x ./ci/*.sh
        - run:
            command: ci/circleci-build-ubuntu-docker.sh
            no_output_timeout: 30m
        - deploy-code
    build-debian-armhf-12-bookworm:
        machine:
            image: ubuntu-2204:current
            resource_class: arm.medium
        environment:
        - OCPN_TARGET: bookworm-armhf
        - DOCKER_IMAGE: arm32v7/debian:bookworm
        - BUILD_FLAGS: -j3
        - BUILD_ENV: debian
        - WX_VER: 32
        - BUILD_GTK3: true
        - DEPLOY_USE_ORB: true
        steps:
        - checkout
        - run: chmod a+x ./ci/*.sh
        - run:
            command: ci/circleci-build-ubuntu-docker.sh
            no_output_timeout: 30m
        - deploy-code
    build-debian-x86_64-12-bookworm:
        machine:
            image: ubuntu-2404:current
        environment:
        - OCPN_TARGET: bookworm
        - BUILD_GTK3: true
        - WX_VER: 32
        - DEPLOY_USE_ORB: true
        - BUILD_ENV: debian
        - DOCKER_IMAGE: debian:bookworm
        steps:
        - checkout
        - run: chmod a+x ci/*.sh
        - run:
            command: ci/circleci-build-ubuntu-docker.sh
            no_output_timeout: 30m
        - deploy-code
    build-debian-armhf-11-bullseye:
        machine:
            image: ubuntu-2204:current
            resource_class: arm.medium
        environment:
        - OCPN_TARGET: bullseye-armhf
        - DOCKER_IMAGE: jongough/debian-armhf:bullseye
        - BUILD_FLAGS: -j3
        - BUILD_ENV: debian
        - BUILD_GTK3: true
        - DEPLOY_USE_ORB: true
        steps:
        - checkout
        - run: chmod a+x ./ci/*.sh
        - run:
            command: ci/circleci-build-ubuntu-docker.sh
            no_output_timeout: 30m
        - deploy-code
    build-debian-arm64-11-bullseye:
        machine:
            image: ubuntu-2204:current
            resource_class: arm.medium
        environment:
        - OCPN_TARGET: bullseye-arm64
        - DOCKER_IMAGE: arm64v8/debian:bullseye-backports
        - BUILD_FLAGS: -j3
        - BUILD_ENV: debian
        - BUILD_GTK3: true
        - DEPLOY_USE_ORB: true
        steps:
        - checkout
        - run: chmod a+x ./ci/*.sh
        - run:
            command: ci/circleci-build-ubuntu-docker.sh
            no_output_timeout: 30m
        - deploy-code
    build-debian-x86_64-11-bullseye:
        machine: 
          image: ubuntu-2004:current
        environment:
        - OCPN_TARGET:  bullseye
        - BUILD_GTK3: true
        - DEPLOY_USE_ORB: true
        - BUILD_ENV: debian
        - DOCKER_IMAGE: opencpn/ci-debian-bullseye-x86_64:latest
        steps:
        - checkout
        - run: >
            echo "deb-src http://ftp.us.debian.org/debian bullseye main"
            | sudo tee -a /etc/apt/sources.list
        - run: >
            echo "deb-src http://ftp.us.debian.org/debian bullseye-updates main"
            | sudo tee -a /etc/apt/sources.list
        - run: cat /etc/apt/sources.list
        - run: chmod a+x ci/*.sh
        - run: ci/circleci-build-debian.sh
        - deploy-code

    build-ubuntu-x86_64-2204-jammy:
      docker:
        - image: cimg/base:edge-22.04
      environment:
        BUILD_GTK3: true
        OCPN_TARGET: jammy
        WX_VER: 32
        DEPLOY_USE_ORB: true
        BUILD_ENV: ubuntu
      steps:
        - checkout
        - run:
            name: "Update apt sources"
            command: |
              echo "deb-src http://us.archive.ubuntu.com/ubuntu/ jammy main" | sudo tee -a /etc/apt/sources.list
              echo "deb-src http://us.archive.ubuntu.com/ubuntu/ jammy-updates main" | sudo tee -a /etc/apt/sources.list
              echo "deb [trusted=yes] https://ppa.launchpadcontent.net/opencpn/opencpn/ubuntu/ jammy main" | sudo tee -a /etc/apt/sources.list
        - run: cat /etc/apt/sources.list
        - run: chmod a+x ci/*.sh
        - run: ci/circleci-build-debian.sh
        - deploy-code


## ---------------------
## OpenCPN 5.6.2 Plugins
## ---------------------

## Appveyor doesn't build for Windows now.
## If below is used, WinXT will not work.
## uncomment if plugin is able to use wxWidget version < 32 (plugin signalk-opencpn-notes requires min. version 32)
#    build-msvc-2022:
#        executor:
#            name: win/server-2022
#            shell: bash.exe
#        environment:
#        - OCPN_TARGET: MSVC
#        - MSVC_VERSION: 2022
#        - WX_VER: 31
#        - WX_VER_PATCH: 2
#        - DEPLOY_USE_ORB: false
#        - APPVEYOR: 1 
#        - CI: ""
#        steps:
#        - checkout
#        - run:
#            privileged: False
#            shell: cmd.exe
#            command: ci\circleci-build-msvc.bat
#        - deploy-code:
#            deploy_use_orb: false
